### ISSUE TITLE
Installation instructions - SNX download link doesn't work

### ISSUE THREAD

**Issue by qrooel** [klimuts/snx-client#9]
CheckPoint SNX Installation Package for Linux OS must be installed first [Download link](https://supportcenter.checkpoint.com/supportcenter/portal/user/anon/page/default.psml/media-type/html?action=portlets.DCFileAction&eventSubmit_doGetdcdetails&fileid=22824)

**Comment by klimuts** [comment]
Sorry for the long reply
Unfortunately, it is no longer possible to download from this link. I will remove it from the description.
